spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    servlet:
      content-type: text/html
